In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,'m'])

In [6]:
a

array(['1', '2', '3', '4', 'm'], dtype='<U11')

In [7]:
b = np.array([1,2,3,4,],dtype = float)

In [8]:
b

array([1., 2., 3., 4.])

In [9]:
c=np.array(['1','2','3','4'],dtype='U11')

In [10]:
c

array(['1', '2', '3', '4'], dtype='<U11')

In [11]:
type(c)

numpy.ndarray

In [8]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
e=([[[1,2,3],[4,5,6],[7,8,9]]])

In [3]:
e

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [12]:
e=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [5]:
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [6]:
d[0,1]

NameError: name 'd' is not defined

In [7]:
d[0][1]

NameError: name 'd' is not defined

In [16]:
d[0,-1]

3

In [11]:
d[0][1]

2

In [13]:
f = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [14]:
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [15]:
f[1,1,2]

12

In [17]:
d[1:4]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
d[1,0:2]#2nd row and column from 0 to 1

array([4, 5])

In [19]:
d[0:2,2]

array([3, 6])

In [20]:
g=np.arange(1,10)

In [21]:
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
g=np.arange(1,10,2)

In [24]:
g

array([1, 3, 5, 7, 9])

In [25]:
g.shape

(5,)

In [28]:
h=np.ones((3,2),dtype=int)

In [29]:
h

array([[1, 1],
       [1, 1],
       [1, 1]])

In [30]:
i=np.zeros((4,4))

In [31]:
i

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
j=np.random.rand(3,2)

In [35]:
j

array([[0.26437814, 0.53369035],
       [0.84939314, 0.66872779],
       [0.26319137, 0.41335699]])

In [36]:
k=np.array([1,2,3,4,5,6])

In [37]:
k

array([1, 2, 3, 4, 5, 6])

In [40]:
k=k.reshape(2,3)

In [39]:
k

array([1, 2, 3, 4, 5, 6])

In [41]:
k

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
k=k.reshape(3,2)

In [43]:
k

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a=np.array([1,2,3])

In [45]:
b=np.array([4,5,6])

In [46]:
np.add(a,b)

array([5, 7, 9])

In [47]:
np.multiply(a,b)

array([ 4, 10, 18])

In [48]:
np.subtract(a,b)

array([-3, -3, -3])

In [49]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [50]:
np.remainder(a,b)

array([1, 2, 3], dtype=int32)

In [51]:
k=k.reshape(-1)

In [52]:
k

array([1, 2, 3, 4, 5, 6])

In [53]:
for i in k:
    print(i)

1
2
3
4
5
6


In [54]:
g=[[1,2,3],[4,5,6]]

In [56]:
for i in g:
    for j in i:
        print(j)

1
2
3
4
5
6


In [57]:
g=[[[1,2,3],[4,5,6]],[[9,10,11],[12,13,14]]]

In [59]:
for i in g:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
9
10
11
12
13
14


In [60]:
for i in np.nditer(g):
    print(i)

(array(1), array(9))
(array(2), array(10))
(array(3), array(11))
(array(4), array(12))
(array(5), array(13))
(array(6), array(14))


In [61]:
j=np.array([1,2,3])

In [62]:
h=np.array([5,6,7])

In [66]:
l=np.concatenate((j,h))

In [67]:
l

array([1, 2, 3, 5, 6, 7])

In [74]:
np.array_split(l,3)

[array([1, 2]), array([3, 5]), array([6, 7])]

In [77]:
f=np.array([[1,2,3],[4,5,6]])

In [73]:
np.array_split(f,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [75]:
np.where(f==4)

(array([1], dtype=int64), array([0], dtype=int64))

In [76]:
np.sort(h)

array([5, 6, 7])

In [78]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
m=np.transpose(f)

In [85]:
j=np.array([[9,10]])

In [86]:
m

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
m=np.append(m,j,axis=0)

In [93]:
v=np.array([[11],[12]])

In [90]:
v

array([[11],
       [12]])

In [ ]:
m_new=np.append()